environment_version: 1
credentials:
- type: aws
  id: qmuXy0MgIWygPReM
  description: AWS Assumable Role - aind-codeocean-user
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: dbm0ohQB5qND97yd
  description: Code Ocean API
  key: API_KEY
  secret: API_SECRET
